//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_v5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DEPARTAMENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTAMENTOS()
        {
            this.PUESTOS = new HashSet<PUESTOS>();
        }

        [Required, DisplayName("ID del Departamento")]
        public int ID_DEPARTAMENTO { get; set; }

        [Required, DisplayName("Departamento")]
        public string NOMBRE { get; set; }

        [Required, DisplayName("Descripción")]
        public string DESCRIPCION { get; set; }

        [Required, DisplayName("Empresa")]
        public int EMPRESA { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUESTOS> PUESTOS { get; set; }
    }
}
