//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_v5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.AMONESTACIONES = new HashSet<AMONESTACIONES>();
            this.ASCENSOS = new HashSet<ASCENSOS>();
            this.HISTORIALES = new HashSet<HISTORIALES>();
            this.PERMISOS = new HashSet<PERMISOS>();
            this.SUSPENSIONES = new HashSet<SUSPENSIONES>();
            this.USUARIOS = new HashSet<USUARIOS>();
            this.VACACIONES = new HashSet<VACACIONES>();
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un ID válido"), DisplayName("ID del Empleado")]
        public int EMP_ID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un ID válido"),
        DisplayName("ID del Empleado"),]
        public string ID_EMPLEADO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese una cédula"), DisplayName("Cédula"), StringLength(9, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 30 caracteres."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inválido.")]
        public string CEDULA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un nombre"),
        DisplayName("Nombre del Empleado"), StringLength(30, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 30 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+[a-zA-ZñÑáéíóúÁÉÍÓÚ]+)*", ErrorMessage = "Formato Inválido.")]
        public string NOMBRE { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese primer apellido"), DisplayName("Primer Apellido"), StringLength(30, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 30 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+[a-zA-ZñÑáéíóúÁÉÍÓÚ]+)*", ErrorMessage = "Formato Inválido.")]
        public string APE1 { get; set; }

        [DisplayName("Segundo Apellido"), StringLength(30, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 30 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+[a-zA-ZñÑáéíóúÁÉÍÓÚ]+)*", ErrorMessage = "Formato Inválido.")]
        public string APE2 { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese una dirección"), DisplayName("Dirección"), DataType(DataType.MultilineText)]
        public string DIRECCION { get; set; }

        [DisplayName("Información Adicional"), DataType(DataType.MultilineText)]
        public string DESCRIPCION { get; set; }

        [DisplayName("Teléfono de Habitación"), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inválido.")]
        public string TEL_HABITACION { get; set; }

        [DisplayName("Teléfono Móvil"), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inválido.")]
        public string TEL_MOVIL { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un correo electrónico válido"), DisplayName("Correo Electrónico "), EmailAddress(ErrorMessage = "Correo Eléctronico con formato inválido")]
        public string E_MAIL { get; set; }

        [DisplayName("Nombre del Puesto"), Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese el puesto del empleado")]
        public int PUESTO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese el salario del empleado"), DisplayName("Salario"), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inválido (Ingrese números.)")]
        public double SALARIO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor seleccione el estado del empleado"), DisplayName("Estado")]
        public string ESTADO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese una fecha de fundación"), DisplayName("Fecha de Nacimiento"), DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FECHA_NAC { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMONESTACIONES> AMONESTACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASCENSOS> ASCENSOS { get; set; }
        public virtual PUESTOS PUESTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIALES> HISTORIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISOS> PERMISOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSPENSIONES> SUSPENSIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VACACIONES> VACACIONES { get; set; }
    }
}
