//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_v5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PUESTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUESTOS()
        {
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
        }

        public int PTS_ID { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un ID válido"), DisplayName("ID del Puesto")]
        public string ID_PUESTO { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un nombre válido"), DisplayName("Nombre del Puesto"), StringLength(45, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 45 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string NOMBRE { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese el estado de la empresa"), DisplayName("Nombre del Departamento")]
        public int DEPARTAMENTO { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un nombre válido"), DisplayName("Nivel Académico"), StringLength(45, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 45 caracteres."), RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Formato Inválido.")]
        public string NIVEL_ACADEMICO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese una experiencia mínima"), DisplayName("Experiencia Mínima"), StringLength(2, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 45 caracteres."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inválido (Ingrese números.)")]
        public string EXP_MIN { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese una experiencia deseada"), DisplayName("Experiencia Deseada") StringLength(2, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 45 caracteres."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inválido (Ingrese números.)")]
        public string EXP_DESEADA { get; set; }

        [DisplayName("Descripción del puesto"), DataType(DataType.MultilineText)]
        public string DESCRIPCION { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese el estado de la empresa"), DisplayName("Estado")]
        public string ESTADO { get; set; }

        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
    }
}
