//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrm_v5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.HISTORIALES = new HashSet<HISTORIALES>();
        }

        public int ID_USUARIO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un nombre"), DisplayName("Nombre de Usuario"), StringLength(25, ErrorMessage = "Nombre muy extenso. Por favor no exceda los 25 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string NOMBRE_USUARIO { get; set; }

        [DisplayName("Contraseña"), Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese la contraseña del usuario"), MinLength(8, ErrorMessage = "La contraseña debe ser de minimo 8 caracteres"), StringLength(16, ErrorMessage = "!Contraseña muy extensa! No exceda lo 16 caracteres")]
        public string CONTRASEÑA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor seleccione el estado del usuario"), DisplayName("Estado"), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string ESTADO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Indique el acceso a este módulo"), DisplayName("Acceso a Empresas"), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string ACC_EMPRESA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Indique el acceso a este módulo"), DisplayName("Acceso a Departamentos"), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string ACC_DEPART { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Indique el acceso a este módulo"), DisplayName("Acceso a Puestos"), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string ACC_PUESTOS { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Indique el acceso a este módulo"), DisplayName("Acceso a Empleados"), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string ACC_EMPLEADOS { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Indique el acceso a este módulo"), DisplayName("Acceso a Expediente"), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string ACC_ACCIONES { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Indique el acceso a este módulo"), DisplayName("Acceso a Usuarios"), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string ACC_USUARIO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Indique el role del Usuario"), DisplayName("Rol"), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inválido.")]
        public string ROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIALES> HISTORIALES { get; set; }
    }
}
